# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data_engineering_zoomcamp',
                'doc_host': 'https://KalleBylin.github.io',
                'git_url': 'https://github.com/KalleBylin/data_engineering_zoomcamp',
                'lib_path': 'data_engineering_zoomcamp'},
  'syms': { 'data_engineering_zoomcamp.core': { 'data_engineering_zoomcamp.core.foo': ( 'core.html#foo',
                                                                                        'data_engineering_zoomcamp/core.py')}}}
