# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-engineering-zoomcamp',
                'doc_host': 'https://KalleBylin.github.io',
                'git_url': 'https://github.com/KalleBylin/data-engineering-zoomcamp',
                'lib_path': 'data_engineering_zoomcamp'},
  'syms': { 'data_engineering_zoomcamp.core': { 'data_engineering_zoomcamp.core.foo': ( 'core.html#foo',
                                                                                        'data_engineering_zoomcamp/core.py'),
                                                'data_engineering_zoomcamp.core.say_hello': ( 'core.html#say_hello',
                                                                                              'data_engineering_zoomcamp/core.py')},
            'data_engineering_zoomcamp.data_ingestion': { 'data_engineering_zoomcamp.data_ingestion.foo': ( 'tutorial.html#foo',
                                                                                                            'data_engineering_zoomcamp/data_ingestion.py'),
                                                          'data_engineering_zoomcamp.data_ingestion.say_hello2': ( 'tutorial.html#say_hello2',
                                                                                                                   'data_engineering_zoomcamp/data_ingestion.py')}}}
