# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tutorial.ipynb.

# %% auto 0
__all__ = ['say_hello2', 'foo']

# %% ../nbs/01_tutorial.ipynb 2
def say_hello2(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/01_tutorial.ipynb 5
def foo(): pass
